### ISSUE TITLE
Gradio Optimizing 

### ISSUE THREAD

**Issue by gitihobo** [facebookresearch/audiocraft#102]
Can we output the wav files to a gradio results folder? Also the browser tab says "gradio" can we change it to "AudioCraft" I use other gradio tabs at the same time and it confuses.

**Comment by rsxdalv** [comment]
You can use the existing webui's projects: https://github.com/facebookresearch/audiocraft/network/dependents
And you can get the code for these features from there as well. 

You can set the title by doing:
with gr.Blocks(title="your title")

**Comment by gitihobo** [comment]
which file would gr.Blocks(title="your title") be at?

**Comment by rsxdalv** [comment]
app.py

**Comment by gitihobo** [comment]
I thought it was already inside the app.py but it doesnt seem to be, I put it in the final line inside app.py but didnt work, anywhere in particular I must copy paste this code?

**Comment by JonathanFly** [comment]
> I thought it was already inside the app.py but it doesnt seem to be, I put it in the final line inside app.py but didnt work, anywhere in particular I must copy paste this code?

It's like this: 

https://github.com/JonathanFly/audiocraft-webui/blob/e54c42a6eced1d96f2a6e9ea41a212b348a2fd7f/app.py#L1200

Note however there is a second launch line, for a shared Gradio space, so you need to edit the right one. Or just both: 

https://github.com/JonathanFly/audiocraft-webui/blob/e54c42a6eced1d96f2a6e9ea41a212b348a2fd7f/app.py#L1654

**Comment by gitihobo** [comment]
Resolved! Only wish now is proper wav output directory but closed issue, thank you both!

**Comment by rsxdalv** [comment]
For output directory and other items you can use a more specialized webui, they are more advanced.
