### ISSUE TITLE
My GPU is not working

### ISSUE THREAD

**Issue by RickyWang111** [facebookresearch/audiocraft#107]
```
F:\Project_Python\audiocraft-main\venv\Scripts\python.exe F:/Project_Python/audiocraft-main/app.py
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.0.1+cu118 with CUDA 1108 (you have 2.0.1+cpu)
    Python  3.9.13 (you have 3.9.12)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
Traceback (most recent call last):
  File "F:\Project_Python\audiocraft-main\app.py", line 35, in <module>
    current_gpu = torch.cuda.current_device()
  File "F:\Project_Python\audiocraft-main\venv\lib\site-packages\torch\cuda\__init__.py", line 674, in current_device
    _lazy_init()
  File "F:\Project_Python\audiocraft-main\venv\lib\site-packages\torch\cuda\__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

Process finished with exit code 1
```

I can run it normally, but it only uses my CPU for work and the speed is too slow!

![image](https://github.com/facebookresearch/audiocraft/assets/96077395/1d439c42-8bcd-44a7-8f12-3f22f9e385d6)

**Comment by thewayur** [comment]
same issue, on running 

`pip install -U xformers
`

it is already installed and i am using A1111 normally

`Requirement already satisfied: xformers in c:\users\gadha\appdata\local\programs\python\python310\lib\site-packages (0.0.20)
Requirement already satisfied: numpy in c:\users\gadha\appdata\local\programs\python\python310\lib\site-packages (from xformers) (1.24.4)
Requirement already satisfied: torch==2.0.1 in c:\users\gadha\appdata\local\programs\python\python310\lib\site-packages (from xformers) (2.0.1)
Requirement already satisfied: pyre-extensions==0.0.29 in c:\users\gadha\appdata\local\programs\python\python310\lib\site-packages (from xformers) (0.0.29)
Requirement already satisfied: typing-inspect in c:\users\gadha\appdata\local\programs\python\python310\lib\site-packages (from pyre-extensions==0.0.29->xformers) (0.9.0)
Requirement already satisfied: typing-extensions in c:\users\gadha\appdata\local\programs\python\python310\lib\site-packages (from pyre-extensions==0.0.29->xformers) (4.7.0)
Requirement already satisfied: filelock in c:\users\gadha\appdata\local\programs\python\python310\lib\site-packages (from torch==2.0.1->xformers) (3.12.2)
Requirement already satisfied: networkx in c:\users\gadha\appdata\local\programs\python\python310\lib\site-packages (from torch==2.0.1->xformers) (3.1)
Requirement already satisfied: sympy in c:\users\gadha\appdata\local\programs\python\python310\lib\site-packages (from torch==2.0.1->xformers) (1.12)
Requirement already satisfied: jinja2 in c:\users\gadha\appdata\local\programs\python\python310\lib\site-packages (from torch==2.0.1->xformers) (3.1.2)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\gadha\appdata\local\programs\python\python310\lib\site-packages (from jinja2->torch==2.0.1->xformers) (2.1.3)
Requirement already satisfied: mpmath>=0.19 in c:\users\gadha\appdata\local\programs\python\python310\lib\site-packages (from sympy->torch==2.0.1->xformers) (1.3.0)
Requirement already satisfied: mypy-extensions>=0.3.0 in c:\users\gadha\appdata\local\programs\python\python310\lib\site-packages (from typing-inspect->pyre-extensions==0.0.29->xformers) (1.0.0)

[notice] A new release of pip available: 22.2.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip`

**Comment by thewayur** [comment]
ok i got it working, install latest python version (also update path manually in evironment variables)

now go to [https://docs.nerf.studio/en/latest/quickstart/installation.html](url)

run in new cmd,
`pip install torch==2.0.1+cu118 torchvision==0.15.2+cu118 --extra-index-url https://download.pytorch.org/whl/cu118`



if neccessary uninstall previous cuda (ref. above link)
pip uninstall torch torchvision functorch tinycudann

**Comment by SaidTorres3** [comment]
> ok i got it working, install latest python version (also update path manually in evironment variables)
> 
> now go to [https://docs.nerf.studio/en/latest/quickstart/installation.html](url)
> 
> run in new cmd, `pip install torch==2.0.1+cu118 torchvision==0.15.2+cu118 --extra-index-url https://download.pytorch.org/whl/cu118`
> 
> if neccessary uninstall previous cuda (ref. above link) pip uninstall torch torchvision functorch tinycudann

IT WORKED, YOU ARE A GENIOUS!!!!
