### ISSUE TITLE
Can a Nvidia 4070 ti with 12gb run medium model?

### ISSUE THREAD

**Issue by jeveloper** [facebookresearch/audiocraft#117]
Apologies for this silly question but as someone fairly new to ML. Would this just fail due to allocation of memory.

Can resizable bar help with the lack of memory on this GPU? 

Thank you kindly.

**Comment by ResidentChief** [comment]
It's running on my 1070 with 8gb VRAM, so definitely

**Comment by jeveloper** [comment]
@ResidentChief  Oh thank you, do you know why specifying a bigger model requires 16gb or more. Is there particular bottleneck that does occur? in README it seems to be pretty clear about memory on GPU.

Thanks

**Comment by ResidentChief** [comment]
I think they are referring to the large model which has over twice the
parameters and thus twice the vram

**Comment by olamedia** [comment]
I was able to run large on 3060, may be because of the drivers.
