### ISSUE TITLE
text conditioning attributes

### ISSUE THREAD

**Issue by hypereikon** [facebookresearch/audiocraft#126]
by looking at './modules/conditioners.py' i realized there are some 'special' text conditioning attributes; 'description', 'key', 'bpm', 'genre', 'moods', 'instrument'.

to use them do i have to prompt in a special way or are normal prompts 'pre-tokenized' into these categories?
or should i do a structured for each categories with quotation marks and all? such as:
`"description": "",
"key": "",
"bpm": "",
"genre": "",
"moods": "",
"instrument": "",`

thx, dont know where else to ask :)

**Comment by hypereikon** [comment]
oh i see now; they have to be used like
```
        [
            ConditioningAttributes(text={"genre": "Rock", "description": "A rock song with a guitar solo"}, wav=...),
            ConditioningAttributes(text={"genre": "Hip-hop", "description": "A hip-hop verse"}, wav=...),
        ]
```
whereas the default _prepare_tokens_and_attributes passes the text_input directly to 'description', not allowing to use the other conditioning attributes
```
attributes = [
            ConditioningAttributes(text={'description': description})
            for description in descriptions]
```

i guess with a custom prepare functions i can dial more in depth to it

**Comment by bluewayg** [comment]
@hypereikon Hi, buddy, can you share how you let bpm etc work in prompt? or in function call? I added sth. like  "100 bpm" "bpm: 100", it just doesn't work. Thanks
