### ISSUE TITLE
Option to continue generation past already sequenced music?

### ISSUE THREAD

**Issue by bulutthecat** [facebookresearch/audiocraft#149]
Would it be possible to use previous tokens to continue generation?
and if so, how could it be implemented using the standard API (torch, audiocraft)?

**Comment by GrandaddyShmax** [comment]
Enjoy 😋
https://github.com/GrandaddyShmax/audiocraft_plus
This Repo has the option to do music continuation of any song of any length, including generated and existing songs
along with that couple of other features.

**Comment by bulutthecat** [comment]
thanks!
