### ISSUE TITLE
My GPU isn't being used... Help please!

### ISSUE THREAD

**Issue by DarqueLilly** [facebookresearch/audiocraft#153]
When I look in task manager, I see python using 56% of CPU while gpu is at 0. I have 2 RTX 2070  supers installed. 
![Taskmgr_h4BBfQoBkt](https://github.com/facebookresearch/audiocraft/assets/111714884/d1eb8693-98f1-4e52-986f-351cf4f46028)
Is it anything i did wrong in installation?

**Comment by mepc36** [comment]
@DarqueLilly did you figure out why your GPU wasn't being used?

**Comment by SaidTorres3** [comment]
https://github.com/facebookresearch/audiocraft/issues/107#issuecomment-1615870036
