### ISSUE TITLE
weights location

### ISSUE THREAD

**Issue by tmc** [facebookresearch/audiocraft#162]
I'm probably being obtuse here but there are references to weights in several locations but I'm not sure where the actual weights are.

**Comment by YellowTech** [comment]
They are hosted on HuggingFace and downloaded automatically through the MusicGen python class, specifically at https://github.com/facebookresearch/audiocraft/blob/main/audiocraft/models/musicgen.py#L88

The HugginFace link for the small model is https://huggingface.co/facebook/musicgen-small where all other models are also listed.
