### ISSUE TITLE
omegaconf.errors.MissingMandatoryValue: Missing mandatory value: datasource.evaluate

### ISSUE THREAD

**Issue by LeooooL** [facebookresearch/audiocraft#165]
Hi, I have a problem executing the following command

dora run solver=musicgen/musicgen_base_32khz model/lm/model_scale=medium continue_from=//pretrained/facebook/musicgen-medium conditioner=text2music

**Comment by LeooooL** [comment]
fixed 

![image](https://github.com/facebookresearch/audiocraft/assets/11988385/8e2319ce-db35-4a28-961c-50d8923b34f0)

**Comment by a624090359** [comment]
useful
