### ISSUE TITLE
You are very big company making a huge push and not even testing 

### ISSUE THREAD

**Issue by FurkanGozukara** [facebookresearch/audiocraft#181]
There are no such thing as                     "./assets/bach.mp3", anymore

So Gradio app fails to launch after your latest update

I am updating my tutorial github readme file for those who are interested in

Moreover I have 1 click auto installer : https://www.patreon.com/posts/ai-music-auto-84334460

Tutorial 

[**Audiocraft / MusicGen - AMAZING Text-To-Music AI Model By Facebook | Tutorial | Better Than MusicLM**](https://youtu.be/v-YpvPkhdO4)

[![image](https://i.imgur.com/8sNXQPK.png)](https://youtu.be/v-YpvPkhdO4)

**Comment by RagedUnicorn** [comment]
I had the same issue. The asset is still there in the assets folder. (https://github.com/facebookresearch/audiocraft/tree/main/assets)

Its just the way how the asset is referenced. Usually it is not a good idea to rely on the script being invoked from a specific path.

The following worked for me

```
python .\demos\musicgen_app.py
```

**Comment by FurkanGozukara** [comment]
> I had the same issue. The asset is still there in the assets folder. (https://github.com/facebookresearch/audiocraft/tree/main/assets)
> 
> Its just the way how the asset is referenced. Usually it is not a good idea to rely on the script being invoked from a specific path.
> 
> The following worked for me
> 
> ```
> python .\demos\musicgen_app.py
> ```

i see
this is definitely relative pathing problem
