### ISSUE TITLE
Code for Multi Band Diffusion - Speech Part

### ISSUE THREAD

**Issue by C00reNUT** [facebookresearch/audiocraft#205]
Hello,

thank you for providing this research to the public. 

Do you plan to provide code for the Speech section from [https://ai.honu.io/papers/mbd](https://ai.honu.io/papers/mbd) ?

I was searching for it in demos, but couldn't find it.

**Comment by Sparker17** [comment]
Hello,

The code for MultiBandDiffusion is the same for all modalities. The pre-trained models are different, you can get the pre-trained models for compression (speech and Music here https://ai.honu.io/papers/mbd) with:

```
mbd = MultiBandDiffusion.get_mbd_24khz(bw=3.0)  # 1.5 or 6.0
```
The pre-trained model compatible with MusicGen is available different : 

```
mbd = MultiBandDiffusion.get_mbd_musicgen()
```
