### ISSUE TITLE
MultiBandDiffusion should pass device to NoiseSchedule

### ISSUE THREAD

**Issue by jn-jairo** [facebookresearch/audiocraft#209]
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

https://github.com/facebookresearch/audiocraft/blob/d6df4f0fff69a69299c5883fae4a4d6d7b8a7948/audiocraft/models/multibanddiffusion.py#L109

Missing device:

```python
schedule = NoiseSchedule(**cfgs[i].schedule, sample_processor=processors[i], device=device)
```

**Comment by Sparker17** [comment]
Fixing it :) Thank you for pointing this !
