### ISSUE TITLE
Allow server_name and server_port command line arguments to be specified when launching gradio

### ISSUE THREAD

**Issue by ashleykleynhans** [facebookresearch/audiocraft#22]
Please allow command line arguments for `server_name` and `server_port` to be specified so that we can allow gradio to listen on all interfaces and a different port when we already have something listening on the default gradio port.

I worked around this for now by changing `demo.launch()` in `app.py` as follows:

```python
demo.launch(server_name="0.0.0.0", server_port=3010)
```

**Comment by FurkanGozukara** [comment]
Also there should be option to start gradio link in browser

**Comment by ashleykleynhans** [comment]
> Also there should be option to start gradio link in browser

I added this to my PR, as well as `--share`.
