### ISSUE TITLE
Unbound local error

### ISSUE THREAD

**Issue by Duraj1** [facebookresearch/audiocraft#241]
![image](https://github.com/facebookresearch/audiocraft/assets/117487302/ce67c882-b323-44ac-a18b-8b1c9679d77f)

I can't run musicgen, I am running it from musicgen_app.py directly from cmd. The webui works as it should, however I can't generate any music
(xformers thing isn't essential, the problem was still there even when I fixed it earlier in venv when following a guide)
I downloaded torchvision via pip install torchvision earlier

**Comment by bartekleon** [comment]
https://github.com/huggingface/transformers/issues/25667

**Comment by bartekleon** [comment]
In short: `pip install protobuf` should do the work. I have protobuf==4.24.1 and it did fix the issue.

**Comment by Duraj1** [comment]
Thanks! It did work
