### ISSUE TITLE
Progressbar values are incorrect

### ISSUE THREAD

**Issue by bartekleon** [facebookresearch/audiocraft#242]
The current token (amount of generated tokens) and total amount of tokens do not match up. (I got 1003/1000 tokens for 20s audio)

1000 makes sense as it's duration (20) * frame_rate (50)

Somewhere in audiocraft.models.lm `generate` function is some issue in counting

**Comment by 0xlws** [comment]
hey @bartekleon, i encountered this as well.

https://github.com/facebookresearch/audiocraft/blob/e96018613ac82b1afe0f0cce7861dfe08ba2b3bf/audiocraft/models/lm.py#L484

`gen_sequence_len` in my case was always 4 tokens more then needed for generation, i think its the padding tokens being counted.
it gets trimmed away in this line:

https://github.com/facebookresearch/audiocraft/blob/e96018613ac82b1afe0f0cce7861dfe08ba2b3bf/audiocraft/models/lm.py#L527

**Comment by adefossez** [comment]
This is because of the delayed pattern, see our paper for detailed. In my opinion this is not really worth fixing, and would require complex interactions between the model and the API code. In the demo we now just cap that number.
