### ISSUE TITLE
protobuf is required to run MusicGen. Why isn't it part of the requirements?

### ISSUE THREAD

**Issue by snatalius** [facebookresearch/audiocraft#247]
I encountered an error while trying to generate music for the first time using MusicGen, and after some troubleshooting I found that I need to pip install protobuf. I'm wondering why it is not installed at the first place. Should it be part of the requirements?

**Comment by 0xlws** [comment]
hey @snatalius i encountered the same, i guess it was overlooked. 
i only came across the same issue myself after not using google colab, adding it to the requirements.txt did solve the issue.
