### ISSUE TITLE
Is there a method of extracting a prompt from a given audio sample?

### ISSUE THREAD

**Issue by slooi** [facebookresearch/audiocraft#249]
Title. This would allow us to find what elements we like in existing audio samples and use them in our music generations

**Comment by carlthome** [comment]
Guess you _could_ view that inverse problem as traditional music auto-tagging but it's not gonna retrieve the prompt itself and rather just predict keywords: https://paperswithcode.com/task/music-auto-tagging

**Comment by adefossez** [comment]
This is not really possible and is an open research question !
