### ISSUE TITLE
Model currupts over 30 seconds

### ISSUE THREAD

**Issue by su77ungr** [facebookresearch/audiocraft#27]
What is the point of this? Why does this model lose its effectiveness with samples that exceed 30 secs?

```python
def set_generation_params(self, use_sampling: bool = True, top_k: int = 250,
                              top_p: float = 0.0, temperature: float = 1.0,
                              duration: float = 60.0, cfg_coef: float = 3.0,
                              two_step_cfg: bool = False):

```

example:

https://github.com/facebookresearch/audiocraft/assets/69374354/b76b7ac5-c766-4857-a523-3bd6c7b36724

**Comment by FurkanGozukara** [comment]
it has thrown me error in gradio app
how did you get 50 :d

**Comment by su77ungr** [comment]
> 

Just edit the package /home/omega/.local/lib/python3.10/site-packages/audiocraft/models/musicgen.py and reset the float
```python
def set_generation_params(self, use_sampling: bool = True, top_k: int = 250,
                              top_p: float = 0.0, temperature: float = 1.0,
                              duration: float = 60.0, cfg_coef: float = 3.0,
                              two_step_cfg: bool = False):

**Comment by wes-kay** [comment]
Assuming this was trained on 30 second clips, lets say n "tokens", you're going to get this unless they release something trained with longer samples.

**Comment by su77ungr** [comment]
> Assuming this was trained on 30 second clips, lets say n "tokens", you're going to get this unless they release something trained with longer samples.

Sure, on the other hand I don't see use cases for 30 second clips besides jingles. This is restrictive

**Comment by wes-kay** [comment]
> Sure, on the other hand I don't see use cases for 30 second clips besides jingles. This is restrictive

**This isn't what I didn't pay for.**

**Comment by rickkadamss** [comment]
This is the same issue for continuation, it is choppy and fuzzy. Any solution?

**Comment by su77ungr** [comment]
> > Sure, on the other hand I don't see use cases for 30 second clips besides jingles. This is restrictive
> 
> **This isn't what I didn't pay for.**

Good one. You do pay them don't you worry.

**Comment by tobq** [comment]
if anyone want to easily use an extended version: [extended model](https://twoshot.ai/model/1)

**Comment by wes-kay** [comment]
> if anyone want to easily use an extended version: [extended model](https://twoshot.ai/model/1)

How is that extended?

**Comment by tobq** [comment]
> > if anyone want to easily use an extended version: [extended model](https://twoshot.ai/model/1)
> 
> How is that extended?

Allows you to generate much more than 30s

**Comment by wes-kay** [comment]
> > > if anyone want to easily use an extended version: [extended model](https://twoshot.ai/model/1)
> > 
> > 
> > How is that extended?
> 
> Allows you to generate much more than 30s

This has nothing to do with this repo.
