### ISSUE TITLE
Failed to train MusicGen on 1 node with multi-GPU

### ISSUE THREAD

**Issue by X-Drunker** [facebookresearch/audiocraft#315]
I want to train MusicGen on single node with multi GPU. But running this command `dora run -d solver=musicgen/musicgen_base_32khz.yaml compression_model_checkpoint=//pretrained/facebook/encodec_32khz transformer_lm.n_q=4 transformer_lm.card=2048` results in only one GPU working. I checked `torch.cuda.device_count()` to ensure the number of GPUs is correct.
 The log is similar to [this](https://github.com/facebookresearch/audiocraft/issues/211#issuecomment-1682113745) and I got this warning
```
/home/aiscuser/.local/lib/python3.8/site-packages/torch/cuda/__init__.py:762: UserWarning: Synchronization debug mode is a prototype feature and does not yet detect all synchronizing operations (Triggered internally at ../torch/csrc/cuda/Module.cpp:830.)
  torch._C._cuda_set_sync_debug_mode(debug_mode)
/scratch/amlt_code/audiocraft/solvers/musicgen.py:220: UserWarning: called a synchronizing CUDA operation (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:148.)
  ce_targets = targets_k[mask_k]
/scratch/amlt_code/audiocraft/solvers/musicgen.py:221: UserWarning: called a synchronizing CUDA operation (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:148.)
  ce_logits = logits_k[mask_k]
```
I wonder how I can successfully train this model with multi-GPUs. Thanks!

**Comment by X-Drunker** [comment]
Found a solution.  `RANK=0` was set in my cluster by default so `start_ddp_workers()` in dora.run didn't execute. Unset this variable helps.

**Comment by ajayarora1235** [comment]
So I'm now able to use `dora run -d` to run training on a 4xA40 one node setup, but my code keeps erroring out due to threading issues. I get the same warnings that you are getting about synchronizing CUDA operations. did you manage to debug those and get training working? @X-Drunker

**Comment by X-Drunker** [comment]
> So I'm now able to use `dora run -d` to run training on a 4xA40 one node setup, but my code keeps erroring out due to threading issues after just one epoch of training and validation. I get the same warnings that you are getting about synchronizing CUDA operations. did you manage to debug those and get training working? @X-Drunker
When I successfully start to train I still get the synchronization warning log, so I think it is not key to the bug. Maybe you should check if the [ddp init method](https://github.com/facebookresearch/audiocraft/blob/e1f2b18f89210ab5a71bc0d31d156d84a8280d9f/audiocraft/train.py#L138C1-L138C1) is running and how it works.

**Comment by ajayarora1235** [comment]
@X-Drunker so just to confirm you didn't have to change any of the source code to get fine tuning to run distributed in full after fixing your environment issue? my code is able to recognize how there are 4 workers, so I'm guessing ddp init is already running. probably an issue with the GPUs I'm using.

**Comment by X-Drunker** [comment]
> @X-Drunker so just to confirm you didn't have to change any of the source code to get fine tuning to run distributed in full after fixing your environment issue? my code is able to recognize how there are 4 workers, so I'm guessing ddp init is already running. probably an issue with the GPUs I'm using.

True. I haven't encountered any threading issue after the training process was launched just with the source code.
