### ISSUE TITLE
xformers installs but could not build wheels for it.

### ISSUE THREAD

**Issue by rer0dgers** [facebookresearch/audiocraft#317]
This is the error I receive: 

File "H:\Program Files\Python311\Lib\site-packages\setuptools\_distutils\util.py", line 139, in convert_path
          raise ValueError("path '%s' cannot be absolute" % pathname)
      ValueError: path '/__w/xformers/xformers/third_party/flash-attention/csrc/flash_attn/flash_api.cpp' cannot be absolute
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for xformers
  Running setup.py clean for xformers
Failed to build xformers
ERROR: Could not build wheels for xformers, which is required to install pyproject.toml-based projects` 

I was able to install xformers 0.0.20 and I was able to remove it and install xformers 0.0.22. 

pip install xformer==0.0.22

I even installed from the source on pypi.org. They all give the same error making wheels. There is an absolute path somewhere that python hates.

**Comment by rer0dgers** [comment]
Here is my current PIP List: H:\MUSIC\audiocraft>pip list
Package            Version
------------------ ------------
certifi            2023.7.22
charset-normalizer 3.3.0
filelock           3.12.4
idna               3.4
Jinja2             3.1.2
MarkupSafe         2.1.3
mpmath             1.3.0
mypy-extensions    1.0.0
networkx           3.1
ninja              1.11.1.1
numpy              1.26.0
Pillow             10.0.1
pip                23.2.1
pyre-extensions    0.0.29
requests           2.31.0
setuptools         65.5.0
sympy              1.12
torch              2.0.1+cu118
torchvision        0.15.2+cu118
typing_extensions  4.8.0
typing-inspect     0.9.0
urllib3            2.0.6
wheel              0.41.2
xformers           0.0.22

**Comment by rer0dgers** [comment]
This is on Windows by the way. Python version 3.11

**Comment by 0xlws** [comment]
looks like there is an issue with latest xformers, 
they did a commit few hours ago, https://github.com/facebookresearch/xformers/commit/16e4245e02f47883b6b43065a0e26dfb12e14e33 so it may be fixed already
if not, an older version (0.0.20) is suggested: https://github.com/facebookresearch/xformers/issues/886#issuecomment-1762922926

**Comment by rer0dgers** [comment]
> looks like there is an issue with latest xformers, they did a commit few hours ago, [facebookresearch/xformers@16e4245](https://github.com/facebookresearch/xformers/commit/16e4245e02f47883b6b43065a0e26dfb12e14e33) so it may be fixed already if not, an older version (0.0.20) is suggested: [facebookresearch/xformers#886 (comment)](https://github.com/facebookresearch/xformers/issues/886#issuecomment-1762922926)

Thanks. I'll give it a try in a few minutes. I did try the older version. It installs too, but the wheels step still errors our. Lets hope they do have it fixed already.

**Comment by rer0dgers** [comment]
Its fixed. Thanks!

**Comment by Isaak-C-Augustus** [comment]
@zeke-john what worked for me (M1) is installing it though a Conda env, you can also try installing it from source.

**Comment by Travis-Barton** [comment]
I'm having the same issue, and i'm in a conda env

**Comment by KeerthanaMurugaraj** [comment]
hello Can you please help me install on M3 ? I am facing the same issue

**Comment by Travis-Barton** [comment]
Can we re-open this?

**Comment by 7maram7** [comment]
having same issue on an Intel Mac

**Comment by adamrg73** [comment]
same issue here intel mac

**Comment by HumzaBasharat** [comment]
> I'm having the same issue, and i'm in a conda env

I'm trying on conda env, is this problem fix on you side.

I the problem fix on your side please let me know how you have fix this issue?

**Comment by Phil-CST-BCIT** [comment]
If you are using Apple MacOS Sequoia 15 and XCode 16, the cause is Apple Clang compiler has disabled the option '-fopenmp'. 

See: [https://mac.r-project.org/openmp/](https://mac.r-project.org/openmp/)

The solution:

1. `brew install llvm`
 
2.  If  **Intel based processor**, do:

```bash 
export CC=/usr/local/opt/llvm/bin/clang
export CXX=/usr/local/opt/llvm/bin/clang++
export LDFLAGS="-L/usr/local/opt/llvm/lib"
export CPPFLAGS="-I/usr/local/opt/llvm/include"
export CMAKE_PREFIX_PATH="/usr/local/opt/llvm"
```

or if you use **Mac silicon**, do

```bash
export CC=/opt/homebrew/opt/llvm/bin/clang
export CXX=/opt/homebrew/opt/llvm/bin/clang++
export LDFLAGS="-L/opt/homebrew/opt/llvm/lib"
export CPPFLAGS="-I/opt/homebrew/opt/llvm/include"
export CMAKE_PREFIX_PATH="/opt/homebrew/opt/llvm"
```

3. `python -m pip install -U audiocraft`

**Comment by ROBERT-MCDOWELL** [comment]
on Mac intel Sonoma, after @Phil-CST-BCIT offered above, I still get:
  Using cached xformers-0.0.22.post7.tar.gz (3.8 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 35, in <module>
        File "/private/var/folders/17/5y1kt25d51jdphls0x_xw1_00000gp/T/pip-install-21lqx3t_/xformers_cd9012245bd64d44904813aed2e34246/setup.py", line 23, in <module>
          import torch
      ModuleNotFoundError: No module named 'torch'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
