### ISSUE TITLE
Add generate_continuation to app.py

### ISSUE THREAD

**Issue by GhostNaN** [facebookresearch/audiocraft#36]
It would be cool if you could add ```generate_continuation``` for the Gradio app.

I was able to hack this together myself by adding a ```gr.Slider``` then modifying the ```predict``` function.
I had it so you could choose where to generate from in the song (with the continuation gr.Slider) and how long (with the duration gr.Slider).
But if you could either add this feature yourself or help guide me in the right direction for a PR I would be grateful.

**Comment by FurkanGozukara** [comment]
yes we need this

supporting

**Comment by Duemellon** [comment]
Can you give us more details so we may do this to our own in the meantime?

**Comment by GhostNaN** [comment]
It's a bit WIP but here you go: [app_new.zip](https://github.com/facebookresearch/audiocraft/files/11713828/app_new.zip)
I'm not a UI expert so I hope the lengthy "Continue from the end duration" is self explanatory.
Otherwise, what it means is that it grabs the last ? seconds from the song and continues the song only from that data.
It does not know about the rest of the song, so how well it continues depends sort of on how long the "end duration" is. 

This is in no way what the PR should look like as I made some modifications to get it to work.
I had to change the the ```gr.Audio``` "Melody Condition" to use filepath and load the audio with ```torchaudio.load``` because for some reason the default way with ```torch.from_numpy(melody[1]).to(MODEL.device).float().t().unsqueeze(0)``` sounded horrible!
I also modified all ```progress``` to true, so no more guessing when the gen will be done within the terminal.

**Comment by FurkanGozukara** [comment]
> @Duemellon It's a bit WIP but here you go: [app_new.zip](https://github.com/facebookresearch/audiocraft/files/11713828/app_new.zip) I'm not a UI expert so I hope the lengthy "Continue from the end duration" is self explanatory. Otherwise, what it means is that it grabs the last ? seconds from the song and continues the song only from that data. It does not know about the rest of the song, so how well it continues depends sort of on how long the "end duration" is.
> 
> This is in no way what the PR should look like as I made some modifications to get it to work. I had to change the the `gr.Audio` "Melody Condition" to use filepath and load the audio with `torchaudio.load` because for some reason the default way with `torch.from_numpy(melody[1]).to(MODEL.device).float().t().unsqueeze(0)` sounded horrible! I also modified all `progress` to true, so no more guessing when the gen will be done within the terminal.

just tested this

progress is very good but still made 29 seconds not the combination of continuing 

here

![image](https://github.com/facebookresearch/audiocraft/assets/19240467/6fa73d4f-50b8-45b6-a020-edf5a4fd00db)

**Comment by GhostNaN** [comment]
@FurkanGozukara 
Yeah, the hard limit of 30 seconds still applies. 
You'll get this error if you try to generate more than that:
```AssertionError: The MusicGen cannot generate more than 30 seconds```

Using more of the song will cut down on the generated playtime. 
So try to balance best you can.

Also, in the screenshot you don't have a "Melody Condition" or song selected so only ```MODEL.generate(descriptions=[text], progress=True)``` will be called.

**Comment by FurkanGozukara** [comment]
> @FurkanGozukara Yeah, the hard limit of 30 seconds still applies. You'll get this error if you try to generate more than that: `AssertionError: The MusicGen cannot generate more than 30 seconds`
> 
> Using more of the song will cut down on the generated playtime. So try to balance best you can.
> 
> Also, in the screenshot you don't have a "Melody Condition" or song selected so only `MODEL.generate(descriptions=[text], progress=True)` will be called.

so this isnt possible?

i mean it generates first 30 seconds, then used that 30 seconds to continue and generate more 30 seconds, so that we can have longer consistent music?

**Comment by GhostNaN** [comment]
> i mean it generates first 30 seconds, then used that 30 seconds to continue and generate more 30 seconds, so that we can have longer consistent music?

I guess if you really want something like that.
You could set the "end duration" to like 15 and "duration" to 30 so you could generate 15 seconds of music.
Then if you somehow exported that to a wav or something.
You could then take that WAV and feed it into the  "Melody Condition" and repeat the process until you have a long enough song.

I could try to get it to do that internally, but as they say "Garbage in, garbage out",
As you are generating now on generated data.
I also think this is a bit overkill for a simple research project.

**Comment by rkfg** [comment]
I managed to generate more than 30 seconds, it can go to infinity in theory. Sample (notice how seamless it is after 30 seconds): 

https://github.com/facebookresearch/audiocraft/assets/184066/52470c06-526d-4c7d-a431-901f7822cbfe

Code is based on demo.ipynb:
```python
import os
import subprocess
from tempfile import NamedTemporaryFile

import torch
from audiocraft.data.audio import audio_write
from audiocraft.models import MusicGen

# Using small model, better results would be obtained with `medium` or `large`.
model = MusicGen.get_pretrained('melody')
model.set_generation_params(
    use_sampling=True,
    top_k=250,
    duration=30
)

overlap = 5
desc = ['80s pop track with bassy drums and synth']

output = model.generate(descriptions=desc, progress=True)
print(output.shape)
last_sec = output[:, :, -overlap*model.sample_rate:]
print(last_sec.shape)
cont = model.generate_continuation(last_sec, model.sample_rate, descriptions=desc, progress=True)
output = torch.cat([output[:, :, :-overlap*model.sample_rate], cont], 2)
output = output.detach().cpu().float()[0]
with NamedTemporaryFile("wb", suffix=".wav", delete=False) as file:
    audio_write(
        file.name, output, model.sample_rate, strategy="loudness",
        loudness_headroom_db=16, loudness_compressor=True, add_suffix=False)
    print(f'Saved to {file.name}')
```
`overlap` sets the number of seconds to take from the generated sample and use for continuation. The second segment also uses the text prompt so the whole song sounds like one. It's a minimalistic example, I suppose it can be easily scaled up to any song length.

**Comment by JonathanFly** [comment]
This is a sliding window it's not breaking any limits. It's like when talk with ChatGPT and you run out of space, you hit the 4000 or 8000 limit. So you copy the last half of your conversation into a new window. 

That said it sounds pretty decent even like this. And if you poke around around the code... wow. Just toys everywhere. It's gonna get a lot better than a sliding window!

**Comment by GhostNaN** [comment]
@JonathanFly 
You took the word out of my mouth.
I'm also surprised to hear it still sound ok.

**Comment by rkfg** [comment]
I think you might want to condition the next segment on the previous one or even pick a random piece to make it interesting. A sliding window is still needed, same as with upscaling in Stable Diffusion where the tiles overlap to hide the seams. But audio conditioning can make it better. I'm currently experimenting with unlimited length, let's see (or rather, hear) how good or bad it is if it's 3 minutes long.

**Comment by rkfg** [comment]
Also not bad though it fades off to just beat in the middle but then recovers:
https://github.com/facebookresearch/audiocraft/assets/184066/b94e3f29-a338-433a-864b-a90358744472

Modified code:
```python
import subprocess
from tempfile import NamedTemporaryFile

import torch
from audiocraft.data.audio import audio_write
from audiocraft.models import MusicGen

# Using small model, better results would be obtained with `medium` or `large`.
model = MusicGen.get_pretrained('melody')
segment_duration = 30
model.set_generation_params(
    use_sampling=True,
    top_k=250,
    duration=segment_duration
)

total_duration = 180
overlap = 5

desc = ['80s pop track with bassy drums and synth']

segment = model.generate(descriptions=desc, progress=True)
total_duration -= segment_duration
while total_duration > 0:
    last_sec = segment[:, :, -overlap*model.sample_rate:]
    next_segment = model.generate_continuation(last_sec, model.sample_rate, descriptions=desc, progress=True)
    segment = torch.cat([segment[:, :, :-overlap*model.sample_rate], next_segment], 2)
    total_duration -= segment_duration - overlap
    if total_duration < segment_duration:
        segment_duration = total_duration + overlap
        model.set_generation_params(
            use_sampling=True,
            top_k=250,
            duration=segment_duration
        )

output = segment.detach().cpu().float()[0]
with NamedTemporaryFile("wb", suffix=".wav", delete=False) as file:
    audio_write(
        file.name, output, model.sample_rate, strategy="loudness",
        loudness_headroom_db=16, loudness_compressor=True, add_suffix=False)
    print(f'Saved to {file.name}')
```
`total_duration` sets the desired duration in seconds, `desc` is the prompt.

**Comment by Alx-AI** [comment]
> Also not bad though it fades off to just beat in the middle but then recovers: https://github.com/facebookresearch/audiocraft/assets/184066/b94e3f29-a338-433a-864b-a90358744472
> 
> Modified code:
> 
> ```python
> import subprocess
> from tempfile import NamedTemporaryFile
> 
> import torch
> from audiocraft.data.audio import audio_write
> from audiocraft.models import MusicGen
> 
> # Using small model, better results would be obtained with `medium` or `large`.
> model = MusicGen.get_pretrained('melody')
> segment_duration = 30
> model.set_generation_params(
>     use_sampling=True,
>     top_k=250,
>     duration=segment_duration
> )
> 
> total_duration = 180
> overlap = 5
> 
> desc = ['80s pop track with bassy drums and synth']
> 
> segment = model.generate(descriptions=desc, progress=True)
> total_duration -= segment_duration
> while total_duration > 0:
>     last_sec = segment[:, :, -overlap*model.sample_rate:]
>     next_segment = model.generate_continuation(last_sec, model.sample_rate, descriptions=desc, progress=True)
>     segment = torch.cat([segment[:, :, :-overlap*model.sample_rate], next_segment], 2)
>     total_duration -= segment_duration - overlap
>     if total_duration < segment_duration:
>         segment_duration = total_duration + overlap
>         model.set_generation_params(
>             use_sampling=True,
>             top_k=250,
>             duration=segment_duration
>         )
> 
> output = segment.detach().cpu().float()[0]
> with NamedTemporaryFile("wb", suffix=".wav", delete=False) as file:
>     audio_write(
>         file.name, output, model.sample_rate, strategy="loudness",
>         loudness_headroom_db=16, loudness_compressor=True, add_suffix=False)
>     print(f'Saved to {file.name}')
> ```
> 
> `total_duration` sets the desired duration in seconds, `desc` is the prompt.

This is exactly what I was looking for, thank you!

**Comment by Duemellon** [comment]
> Also not bad though it fades off to just beat in the middle but then recovers: https://github.com/facebookresearch/audiocraft/assets/184066/b94e3f29-a338-433a-864b-a90358744472

That's amazing. Do I need to create a new file & save this code to it? or add this to the demo.ipmb file? 

Is this for the Gradio or only command line? Is this a switch/option to enable or it would be enabled by default?

Sorry for so many questions. I can wait until something more friendly is implemented as well seeing as this is moving at the speed of light right now -- No need for me to hop on a moving train if I can get to the destination it's going to.

**Comment by rkfg** [comment]
Put it to a new file, for example, `gen.py`, make changes in prompt/duration if you want and run it as `python gen.py`, that's it. Command-line only, I'm not familiar with Gradio. I'm actually not very familiar with Python and Torch either 😄 But you can experiment with it right now, it's not hard to change the text and re-run the script.

**Comment by Duemellon** [comment]
> I added this feature to the web UI, see my branch `long` here: https://github.com/rkfg/audiocraft/tree/long The duration is now limited by 3600 seconds (a sane limitation, not technical) and overlap can go up to 29 seconds. Feel free to test!

Thanks for this! But I just used this to update:

git pull https://github.com/rkfg/audiocraft.git long

And I'm getting errors when trying to generate anything right now:

Loading model medium
Segment duration: 30, duration: 60, overlap: 10
Segment duration: 30, duration: 30, overlap: 10
Segment duration: 20, duration: 10, overlap: 10
CLIPPING C:\Users\dueme\AppData\Local\Temp\tmp88n4b2_v.wav happening with proba (a bit of clipping is okay): 2.0833333564951317e-06 maximum scale:  1.173307180404663
E:\audiocraft\venv\lib\site-packages\matplotlib\axes\_axes.py:2229: RuntimeWarning: overflow encountered in scalar add
  dx = [convert(x0 + ddx) - x for ddx in dx]
E:\audiocraft\venv\lib\site-packages\matplotlib\axes\_axes.py:2229: RuntimeWarning: overflow encountered in scalar subtract
  dx = [convert(x0 + ddx) - x for ddx in dx]
E:\audiocraft\venv\lib\site-packages\matplotlib\patches.py:739: RuntimeWarning: overflow encountered in scalar add
  y1 = self.convert_yunits(self._y0 + self._height)
'ffmpeg' is not recognized as an internal or external command,
operable program or batch file.

**Comment by rkfg** [comment]
Probably ffmpeg is not installed, I haven't modified anything related to it so check if your setup is correct. It's easier to add a new remote to the existing repo like this:
```
git remote add rkfg https://github.com/rkfg/audiocraft.git
git fetch rkfg
git checkout long
```

**Comment by Duemellon** [comment]
I didn't have FFmpeg installed before as part of the install process. I used the directions provided here: 
https://github.com/FurkanGozukara/Stable-Diffusion/blob/main/Tutorials/AI-Music-Generation-Audiocraft-Tutorial.md

The line-by-line manual install.

I'll look into FFmpeg. I think I had to have had it installed at some point, somewhere. So many of these things mention it.

**Comment by rkfg** [comment]
Weird that it worked before because ffmpeg is required to create the working video with audio. Maybe it comes with some of the dependencies? I use Linux and ffmpeg was installed long ago from the repo so I'm out of ideas. The official README says you should have it installed.

**Comment by Duemellon** [comment]
OK. I just installed using the same directions as before & it generates & plays songs. What I think is related to it working is the step that includes:

_git checkout 0c75a46321e6e4b15b1e6c751d9c69ff9cbdda69_

but I don't really know what that command means or does.

After that I just ran your steps from within my Audiocraft folder

git remote add rkfg https://github.com/rkfg/audiocraft.git
git fetch rkfg
git checkout long

OK, after the install of your fork still the FFmpeg error. I'll investigate getting it installed or configured right.

**Comment by rkfg** [comment]
There were many changes after that commit, I think the ffmpeg requirement was added after it. You can try to rebase my commits to 0c75a46321e6e4b15b1e6c751d9c69ff9cbdda69 but I don't think it's a good idea. Rather fix the dependencies on your machine to make the current version work. In fact you just need to get `ffmpeg.exe` from the official source and put it somewhere the program can find it, like in the audiocraft directory or C:/Windows etc. If you can run it from cmd by typing `ffmpeg` then you should be good.

**Comment by Duemellon** [comment]
Ah... so the "joke" was that I did have it installed but for Automatic1111's SD & how/where it was installed was under that directory. I reinstalled ffmpeg to a folder off the C: & updated the Windows system path -- I got sounds now.

Checked my first 60 sec take off of the Melody model & worked exactly as described.

Did a 3 min version & there was a prob -- it just died out & went silent at the ½-way mark. No more sound. https://ufile.io/oncxcjpi

Thank you for doing this. I'm glad this is getting all this attention & love that it deserves! AI is "for the people" & thank you for being part of that movement.

**Comment by rkfg** [comment]
Yes, sometimes it ends the song and might start a new one (or not). Same as with SD, it's not perfect but it's free so you can keep trying and picking the results that work. Maybe it can be fixed with more clever changes like conditioning and retrying generation if the output is silent or cut.

I will keep updating my fork, not sure if these changes warrant a PR. I want to add a progress bar and a queue to make the instance semi-public for my friends. Without the queue it might get overwhelmed. Adding a seed is also important to be able to reproduce generations.

**Comment by FurkanGozukara** [comment]
> I managed to generate more than 30 seconds, it can go to infinity in theory. Sample (notice how seamless it is after 30 seconds):
> 
>  sample.mp4 
> Code is based on demo.ipynb:
> 
> ```python
> import os
> import subprocess
> from tempfile import NamedTemporaryFile
> 
> import torch
> from audiocraft.data.audio import audio_write
> from audiocraft.models import MusicGen
> 
> # Using small model, better results would be obtained with `medium` or `large`.
> model = MusicGen.get_pretrained('melody')
> model.set_generation_params(
>     use_sampling=True,
>     top_k=250,
>     duration=30
> )
> 
> overlap = 5
> desc = ['80s pop track with bassy drums and synth']
> 
> output = model.generate(descriptions=desc, progress=True)
> print(output.shape)
> last_sec = output[:, :, -overlap*model.sample_rate:]
> print(last_sec.shape)
> cont = model.generate_continuation(last_sec, model.sample_rate, descriptions=desc, progress=True)
> output = torch.cat([output[:, :, :-overlap*model.sample_rate], cont], 2)
> output = output.detach().cpu().float()[0]
> with NamedTemporaryFile("wb", suffix=".wav", delete=False) as file:
>     audio_write(
>         file.name, output, model.sample_rate, strategy="loudness",
>         loudness_headroom_db=16, loudness_compressor=True, add_suffix=False)
>     print(f'Saved to {file.name}')
> ```
> 
> `overlap` sets the number of seconds to take from the generated sample and use for continuation. The second segment also uses the text prompt so the whole song sounds like one. It's a minimalistic example, I suppose it can be easily scaled up to any song length.

amazing we need this for gradio

can someone make a pull request for this for gradio? i sck at gradio :/

**Comment by rkfg** [comment]
I literally implemented it in Gradio a few comments above xD

**Comment by FurkanGozukara** [comment]
> I didn't have FFmpeg installed before as part of the install process. I used the directions provided here: https://github.com/FurkanGozukara/Stable-Diffusion/blob/main/Tutorials/AI-Music-Generation-Audiocraft-Tutorial.md
> 
> The line-by-line manual install.
> 
> I'll look into FFmpeg. I think I had to have had it installed at some point, somewhere. So many of these things mention it.

added ffmpeg to the steps with instructions

**Comment by GhostNaN** [comment]
@rkfg 
> Adding a seed is also important to be able to reproduce generations.

You can do that by using pytorch_seed.
I've done this before with bark all you need to add is something like this before you generate:
```python
import pytorch_seed

seed = 555
with pytorch_seed.SavedRNG(seed):
    # Your gen code here
```

**Comment by rkfg** [comment]
@GhostNaN Thanks, I'll take a look!

**Comment by FurkanGozukara** [comment]
> I literally implemented it in Gradio a few comments above xD

just tested and i got this error weird

```
Traceback (most recent call last):
  File "F:\audiocraft\venv\lib\site-packages\gradio\routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "F:\audiocraft\venv\lib\site-packages\gradio\blocks.py", line 1346, in process_api
    result = await self.call_function(
  File "F:\audiocraft\venv\lib\site-packages\gradio\blocks.py", line 1074, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "F:\audiocraft\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "F:\audiocraft\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "F:\audiocraft\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "F:\audiocraft\app_new.py", line 90, in predict
    audio_write(
TypeError: audio_write() got an unexpected keyword argument 'loudness_compressor'
```

**Comment by rkfg** [comment]
Make sure your git repo is clean, looks like you're running some `app_new.py` file which doesn't exist in my fork.

**Comment by FurkanGozukara** [comment]
> Make sure your git repo is clean, looks like you're running some `app_new.py` file which doesn't exist in my fork.

ah i was using your file on official repo :d 

if we need to modify more files then i can't update my readme file :/

**Comment by FurkanGozukara** [comment]
> Make sure your git repo is clean, looks like you're running some `app_new.py` file which doesn't exist in my fork.

i added repo link : https://github.com/FurkanGozukara/Stable-Diffusion/blob/main/Tutorials/AI-Music-Generation-Audiocraft-Tutorial.md

**Comment by rkfg** [comment]
I only updated app.py. Probably you've copied this file from my repo to an outdated official repo which lacks this parameter. Either use my fork (it's based on `main`) or update your official repo to the last commit and copy the file over.

**Comment by FurkanGozukara** [comment]
> I only updated app.py. Probably you've copied this file from my repo to an outdated official repo which lacks this parameter. Either use my fork (it's based on `main`) or update your official repo to the last commit and copy the file over.

oh let me test. yes i hadn't had updated

**Comment by Duemellon** [comment]
Hey RKFG

Could you consider giving an option to turn on/off kind of a loopback feature for continuation?

Meaning:
Right now the song meanders from the original composition over time, by the nature of it having that "grid" format where it samples the last seconds of the song & riffs off of it. 

- This can definitely lead to compositions that sound more like a jam session -- which might be what is wanted.

- But what about something that reuses the 1st completed block as the "Melody input" for the remaining variations but IN A WAY that still samples the last 5-10 seconds (or whatever parameter)? 

I think that would also prevent the spiraling decibel oblivion

**Comment by FurkanGozukara** [comment]
updated my readme file with @rkfg file

https://github.com/FurkanGozukara/Stable-Diffusion/blob/main/Tutorials/AI-Music-Generation-Audiocraft-Tutorial.md

tutorial video : https://www.youtube.com/watch?v=v-YpvPkhdO4

and here 1 minute song generation 

https://github.com/facebookresearch/audiocraft/assets/19240467/e879b4b2-4a15-4409-a0bd-185ca3b6e1f0

**Comment by rkfg** [comment]
Yeah, I'll try that too. The existing continuation function doesn't accept melody but it's just a missing parameter I think. Meanwhile I added a progress bar in my fork.

**Comment by Duemellon** [comment]
oh... one new thought (I'm not sure how well it would be received by others) but instead of presuming a 30-sec block to be appended, how's about that being a separate value of 1-30 so that someone could be a bit more precise since the Audiocraft does understand measure & BPM 

it knows what a 3/4 is v. 4/4 & BPM, so someone who is a musician, like me, could "math out" the exact time it takes for that movement to end & basically prompt it to only construct it that way

IDK if that's getting too deep into the woods on that one since the math won't be intuitive for everyone... hold on. I'll try to come up with a formula to do the calc in the GUI...

**Comment by Duemellon** [comment]
Like this...

https://toolstud.io/music/song-length.php

**Comment by FurkanGozukara** [comment]
> oh... one new thought (I'm not sure how well it would be received by others) but instead of presuming a 30-sec block to be appended, how's about that being a separate value of 1-30 so that someone could be a bit more precise since the Audiocraft does understand measure & BPM
> 
> it knows what a 3/4 is v. 4/4 & BPM, so someone who is a musician, like me, could "math out" the exact time it takes for that movement to end & basically prompt it to only construct it that way
> 
> IDK if that's getting too deep into the woods on that one since the math won't be intuitive for everyone... hold on. I'll try to come up with a formula to do the calc in the GUI...

how do you prompt? i have 0 music skills :D

**Comment by Alx-AI** [comment]
Does anyone know if it would be possible to merge generate_continuation and generate_with_chroma so that you could take a source track, split it into <=30 second chunks, use the corresponding chunk for each segment as driving melody; while also having each following chunk be a 'continuation' of the prior?

**Comment by Duemellon** [comment]
> how do you prompt? i have 0 music skills :D

I started a Whyp but now the file format changed from WAVE to mp4. https://www.whyp.it/users/17948/duemellon

But, here's a generality:

120bpm - beats per minute. Typical dance songs are 120. Most ballads are 90-100. A real slow song is 70-85. 140+ is the kinda stuff for raves, techno, & dub

320kbps 48khz - these ensure quality of the recordings, reducing hiss & usually expanding the sound range. These numbers are just rather high for an MP3  recording but not near the values of a raw audio recording. Don't apply this to sound that is supposed to be LOFI (like Lofi hip hop) because it undoes their intent : ) 22kbps quality should start sounding like you're listening to a song through a telephone or through a megaphone

4/4, 3/4, 5/4, 2/4, etc -- This would have to get into a bit more about music theory that would be applicable here. Just know the majority of American pop songs (the huge VAST majority) is 4/4. Slow jams & waltz are 3/4 (ballads & such). 5/4 & others are more for non-US audiences that have a Spanish influence. 13/8, 11/8, 10/7, etc. "weird" numbers would be for jazz

Have fun with that stuff!

**Comment by FurkanGozukara** [comment]
> Does anyone know if it would be possible to merge generate_continuation and generate_with_chroma so that you could take a source track, split it into <=30 second chunks, use the corresponding chunk for each segment as driving melody; while also having each following chunk be a 'continuation' of the prior?
> 
> (I imagine setting a consistent seed would help here as well)

this is already added in a fork repo

i updated my file for instructions : https://github.com/FurkanGozukara/Stable-Diffusion/blob/main/Tutorials/AI-Music-Generation-Audiocraft-Tutorial.md

**Comment by FurkanGozukara** [comment]
@Duemellon so the model understands this keywords : 4/4 100bpm 320kbps 48khz motown groove

i wish we would have training dataset keywords

**Comment by Duemellon** [comment]
> @Duemellon so the model understands this keywords : 4/4 100bpm 320kbps 48khz motown groove
> 
> i wish we would have training dataset keywords

Yah, it'd be nice. You did also see my other examples? I was editing the post so not sure if you saw them before moving on. I guess i'll just update my discoveries onto the Reddit page. I see someone else, [rsxdalv](https://github.com/rsxdalv), setup a page to upload files & I think they saw my Reddit post with that 320/48 discovery. 

Just, you know, however we get it out there, right?

**Comment by FurkanGozukara** [comment]
posted 1 min example on twitter

https://twitter.com/GozukaraFurkan/status/1668006422448054274

**Comment by FurkanGozukara** [comment]
> > @Duemellon so the model understands this keywords : 4/4 100bpm 320kbps 48khz motown groove
> > i wish we would have training dataset keywords
> 
> Yah, it'd be nice. You did also see my other examples? I was editing the post so not sure if you saw them before moving on. I guess i'll just update my discoveries onto the Reddit page. I see someone else, [rsxdalv](https://github.com/rsxdalv), setup a page to upload files & I think they saw my Reddit post with that 320/48 discovery.
> 
> Just, you know, however we get it out there, right?

may i get your reddit page address please

**Comment by rkfg** [comment]
Seed added with the customary SD-like random/reuse buttons

**Comment by Duemellon** [comment]
just so I don't accidentally screw myself over... what is the update command I should be using for this fork?

**Comment by Duemellon** [comment]
It does seem like the songs thin themselves out at they extend using that time overlap

**Comment by rkfg** [comment]
You can use `git pull` I suppose. If it doesn't work do `git branch --set-upstream-to=rkfg/long` and then try `git pull` again.

I added the interrupt button, it can't stop the current segment processing but will stop after it and return whatever was generated.

**Comment by Duemellon** [comment]
> You can use `git pull` I suppose. If it doesn't work do `git branch --set-upstream-to=rkfg/long` and then try `git pull` again.

Tried _git pull_  first but got this error:

_Traceback (most recent call last):
  File "E:\audiocraft\app.py", line 15, in <module>
    from audiocraft.models import MusicGen
  File "E:\audiocraft\audiocraft\__init__.py", line 8, in <module>
    from . import data, modules, models
  File "E:\audiocraft\audiocraft\models\__init__.py", line 8, in <module>
    from .musicgen import MusicGen
  File "E:\audiocraft\audiocraft\models\musicgen.py", line 30, in <module>
    class MusicGen:
  File "E:\audiocraft\audiocraft\models\musicgen.py", line 124, in MusicGen
    def generate_unconditional(self, num_samples: int, progress: bool|tp.Callable[[int, int], None] = False) -> torch.Tensor:
TypeError: unsupported operand type(s) for |: 'type' and '_CallableGenericAlias'_

Then tried the _git branch..._ command but it says "already up to date" when I give it git pull afterwards. Received same errors : (

**Comment by rkfg** [comment]
I used typing that was apparently added in python 3.10. I'll see if I can downgrade it or you can update python to 3.10.

**Comment by rkfg** [comment]
Pushed a fix, should work now

**Comment by rkfg** [comment]
Added conditioning for next chunks with the first chunk, not sure if it works like expected. Try it!

**Comment by Alx-AI** [comment]
> Added conditioning for next chunks with the first chunk, not sure if it works as expected. Try it!

Is it possible to condition on the right section of the original song instead of the previous chunk?
e.g. I have a 150 second song, its split into 5 chunks, each chunk conditions on the original song's chunk but after the first one is made, each following one is a continuation of the newly generated clip.

**Comment by Duemellon** [comment]
Render time dramatically increased (I guess that's the price we pay).

Now, instead of the risk of decibel oblivion there always seems to be a "build", meaning it continues to add more as goes on. Not so dramatically, but there's definitely more. Probably not so noticeable to the average listener. It would be a problem if I tried to loop it.

It seems this method relies heavily on the baseline/beat for it's identity -- meaning, that barely changes. No drum fills, or rhythm changes, or even more drumline additions. Maybe that's my prompting? IDK. Again, most people would focus on the consistency of the beat more than the accompaniment so that probably works for others.

If I had my magic wand I'd add this:
- an option of "1st chuck referencing" or not

- and then a slider for the "don't reference" from 0-120 (or whatever number) that is a "trailing reference" that basically says 
If this is set to 30 then we ref 30 sec prior. 65? Then 65 sec prior. But I know the sample max is still 30 so it'd be checking the last 65-35 sec.

And I'll do some tests to see if the Top-k/p & CFG effect the production -- if it deviates the drum/bassline, if it builds (adds sounds) or we get decibel death. I'lll get back to you on that.

Thanks! This solution is DEFINITELY better than it was prior. YOu've been at this all day -- don't forget to hydrate.

**Comment by rkfg** [comment]
It always uses the first chunk for conditioning and last X (overlap) seconds for continuation. I think this is exactly why it messes up generation, because it goes off beat. Might not be easy to solve, so I've disabled it by default for now.

**Comment by FurkanGozukara** [comment]
> It always uses the first chunk for conditioning and last X (overlap) seconds for continuation. I think this is exactly why it messes up generation, because it goes off beat. Might not be easy to solve, so I've disabled it by default for now.
> 
> BTW, looks like PRs require signing a CLA which I'm not gonna do so these patches will most probably stay only in my fork.

trying last commit getting this error

by the way i can make a pull request by using your fork if you allow

```
Traceback (most recent call last):
  File "F:\audiocraft\venv\lib\site-packages\gradio\routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "F:\audiocraft\venv\lib\site-packages\gradio\blocks.py", line 1346, in process_api
    result = await self.call_function(
  File "F:\audiocraft\venv\lib\site-packages\gradio\blocks.py", line 1074, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "F:\audiocraft\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "F:\audiocraft\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "F:\audiocraft\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "F:\audiocraft\music_gen_infinite_lenght.py", line 100, in predict
    next_segment = MODEL.generate_continuation(last_chunk,
TypeError: MusicGen.generate_continuation() got an unexpected keyword argument 'melody_wavs'
```

**Comment by rkfg** [comment]
Same as above, you've probably not updated the rest of the repo. I might change other files, not only app.py.

**Comment by FurkanGozukara** [comment]
> Same as above, you've probably not updated the rest of the repo. I might change other files, not only app.py.

i see yes i didnt used your repo :/ just used app.py file

**Comment by rkfg** [comment]
Please just use the `long` branch and update it with git pull. Also, I can't prohibit merging my changes but I'm not going to endorse that either. I'm strictly against these corporate agreements they force you to sign just to contribute.

**Comment by Duemellon** [comment]
that's what the CLA is? a corporate license agreement? ugh. Yah. Thanks for your effort on this.

**Comment by GhostNaN** [comment]
If no one as any objections, this feature has been added to the main repo and this issue can now be closed.

Thank you all for your excellent work and collaboration!

**Comment by WyrmSpear** [comment]
What line do we need to change to make the default save as a .wav or .mp3 instead of .mp4?

**Comment by 0xdevalias** [comment]
> What line do we need to change to make the default save as a .wav or .mp3 instead of .mp4?

@WyrmSpear That probably depends on how/where you're running it. I'm guessing you're using one of the colabs? If so, which one?

**Comment by WyrmSpear** [comment]
Actually just running the linked to audiocraft-long fork code on local runtime, would love to splice this code together with that multi prompt as well that could be a real composition changer

**Comment by hubbybenjamin** [comment]
Does this let you generate like an hour of song?

**Comment by adenta** [comment]
@hubbybenjamin curious what you found, if it let you generate super long songs

**Comment by NitinNR** [comment]
> ```python
>     next_segment = model.generate_continuation(last_sec, model.sample_rate, descriptions=desc, progress=True)
> ```

can anyone explain this line by line !

**Comment by NitinNR** [comment]
> Also not bad though it fades off to just beat in the middle but then recovers: https://github.com/facebookresearch/audiocraft/assets/184066/b94e3f29-a338-433a-864b-a90358744472
> 
> Modified code:
> 
> ```python
> import subprocess
> from tempfile import NamedTemporaryFile
> 
> import torch
> from audiocraft.data.audio import audio_write
> from audiocraft.models import MusicGen
> 
> # Using small model, better results would be obtained with `medium` or `large`.
> model = MusicGen.get_pretrained('melody')
> segment_duration = 30
> model.set_generation_params(
>     use_sampling=True,
>     top_k=250,
>     duration=segment_duration
> )
> 
> total_duration = 180
> overlap = 5
> 
> desc = ['80s pop track with bassy drums and synth']
> 
> segment = model.generate(descriptions=desc, progress=True)
> total_duration -= segment_duration
> while total_duration > 0:
>     last_sec = segment[:, :, -overlap*model.sample_rate:]
>     next_segment = model.generate_continuation(last_sec, model.sample_rate, descriptions=desc, progress=True)
>     segment = torch.cat([segment[:, :, :-overlap*model.sample_rate], next_segment], 2)
>     total_duration -= segment_duration - overlap
>     if total_duration < segment_duration:
>         segment_duration = total_duration + overlap
>         model.set_generation_params(
>             use_sampling=True,
>             top_k=250,
>             duration=segment_duration
>         )
> 
> output = segment.detach().cpu().float()[0]
> with NamedTemporaryFile("wb", suffix=".wav", delete=False) as file:
>     audio_write(
>         file.name, output, model.sample_rate, strategy="loudness",
>         loudness_headroom_db=16, loudness_compressor=True, add_suffix=False)
>     print(f'Saved to {file.name}')
> ```
> 
> `total_duration` sets the desired duration in seconds, `desc` is the prompt.

please anyone explain this line by line !
