### ISSUE TITLE
MAGNeT inference failing with ValueError: Invalid shape for attention bias

### ISSUE THREAD

**Issue by nateraw** [facebookresearch/audiocraft#390]
Hey there! :) Thank you for the awesome work here.

Really looking forward to playing with the MAGNeT models, but getting the following when running inference with the new MAGNeT model source code from the `main` branch.

```
ValueError: Invalid shape for attention bias: torch.Size([498, 498]) (expected (6, 16, 498, 498))
  query.shape: torch.Size([6, 498, 16, 64])
  key.shape  : torch.Size([6, 498, 16, 64])
  value.shape: torch.Size([6, 498, 16, 64])
```

Reproducible example in Colab (including full stack trace) here: https://gist.github.com/nateraw/4b5fb6d62a37df83e3528f410ad438c9

CC @lonzi, as you were the one who merged this.

**Comment by xpeng** [comment]
comfirmed when using model magnet-medium-30secs.
```
ValueError: Invalid shape for attention bias: torch.Size([1500, 1500]) (expected (4, 24, 1500, 1500))
  query.shape: torch.Size([4, 1500, 24, 64])
  key.shape  : torch.Size([4, 1500, 24, 64])
  value.shape: torch.Size([4, 1500, 24, 64])
```

**Comment by singhaki** [comment]
seems like issue with all checkpoint’s. i tried all the models but didn't work. all of them was throwing shape error.

**Comment by singhaki** [comment]
how is the output after this? @mkfold

**Comment by lonzi** [comment]
Hi @nateraw, @xpeng @singhaki @mkfold.
Thanks for pointing out on this issue! We reproduced it and we will fix it ASAP.

**Comment by joe-none416** [comment]
another temp work around, I followed [link](https://colab.research.google.com/github/camenduru/MAGNET-colab/blob/main/MAGNET_colab.ipynb#scrollTo=VjYy0F2gZIPR) and recompile xformers with version=v0.0.20, and it works.

**Comment by lonzi** [comment]
Yeah this should be indeed a valid workaround. 
I see that the current code works for:
xformers                  0.0.20+6425fd0.d20230502

And doesn't work for:
xformers                  0.0.22.post7

We will try make it compatible for both

**Comment by lonzi** [comment]
@nateraw  @xpeng  @singhaki  @mkfold - see our fix in:
https://github.com/facebookresearch/audiocraft/commit/7dece43a4d186e47e5e1c67983ed10a99f225948

Should be both xformers 0.0.20 and 0.0.22 compatible. This is still under testing and review, and wasn't merged to main branch yet.

**Comment by lonzi** [comment]
Fixed in:
https://github.com/facebookresearch/audiocraft/commit/2a5c5e971915aa03bd99defe44bde2a4bebb4361

closing the issue.

**Comment by lonzi** [comment]
Fixed in:
https://github.com/facebookresearch/audiocraft/commit/2a5c5e971915aa03bd99defe44bde2a4bebb4361

closing the issue.
