### ISSUE TITLE
Getting it running on a secondary GPU

### ISSUE THREAD

**Issue by zarriente** [facebookresearch/audiocraft#40]
How would I get it to run on a secondary GPU? Like how for Stable Diffusion you put "set CUDA_VISIBLE_DEVICES=1" in the batch file.

**Comment by fungiboletus** [comment]
It doesn't work for you ? I used this environment variable successfully.

**Comment by zarriente** [comment]
> It doesn't work for you ? I used this environment variable successfully.

In MusicGen/Audiocraft? If so, where do you put it. It does work for me in SD, but I wouldn't know where to put it for MusicGen/audiocraft.

**Comment by fungiboletus** [comment]
It's an environment variable, you can ask chatgpt the details for your environment.

**Comment by zarriente** [comment]
Well, I figured it out. I just put:

import os
os.environ['CUDA_VISIBLE_DEVICES']='1'

before "import torch" in app.py

**Comment by jasonmhead** [comment]
To make it more extensible you can add the following so you can choose at startup what gpu to use:

Put this at the head of the app.py file:

```
import os
import argparse

# Parse command line argument
parser = argparse.ArgumentParser(description='GPU Switcher')
parser.add_argument('--gpu', type=int, default=0, help='Index of the GPU to use (default: 0)')
args = parser.parse_args()
    
# Set the CUDA_VISIBLE_DEVICES environment variable
os.environ['CUDA_VISIBLE_DEVICES'] = str(args.gpu)
```

and below ```import torch```

you can add

```
current_gpu = torch.cuda.current_device()
current_gpu_name = torch.cuda.get_device_name(current_gpu)
print ("Current GPU is "+str(current_gpu)+" : "+current_gpu_name)
```

for startup verification

and add 

```
parser.add_argument(
        '--gpu', help='set gpu'
    )
```

in the ```if __name__ == "__main__": ```

section so the script doesn't fail later
