### ISSUE TITLE
Longer prompt results in CUDA out of memory

### ISSUE THREAD

**Issue by AtanasValkov** [facebookresearch/audiocraft#47]
When using the provided example code any prompt that is longer than 2-5 words results in a out of memory error. This must be something with how this method differs from the gradio UI generation, since there I can generate with the medium model with much longer prompts without running out of memory on the same machine. The error happens specifically on the line model.generate(prompt)

```
  model = MusicGen.get_pretrained('small')
  model.set_generation_params(duration=8)
  wav = model.generate(prompt)
  for idx, one_wav in enumerate(wav):
  # Will save under {idx}.wav, with loudness normalization at -14 db LUFS.
      file_path = audio_write(f'music/{prompt}', one_wav.cpu(), model.sample_rate, strategy="loudness")
```

After some debugging I assume the issue might be due to package version issues, where my project that is trying to utilize a different version of torch or transformers than the audiocraft ones.

Solution: I didn't see that model.generate doesn't take a string but instead a list. The correct way to call it:
model.generate(descriptions=[prompt])

**Comment by FurkanGozukara** [comment]
i tried very long ones and didn't get any error weird

you can see in my tutorial video : https://youtu.be/v-YpvPkhdO4
