### ISSUE TITLE
melody model architecture: is demucs used only when training or is it used at inference too?

### ISSUE THREAD

**Issue by HugoF-Silva** [facebookresearch/audiocraft#478]
demucs is used to separate each track of the input audio. By default, you compute chromagram from melody track 
(melody track == everything that isn't drum and bass; and this drop of drum and bass tracks is done by default).

I know this is done when training, **but the chromagram used as condition when infering is also a chromagram based only on melody or is a chromogram based on the entire input audio?**

i.e.,
do you expect that the user, when infering:
will input an audio that has only melody?
or,
will input an audio that maybe doesn't have only melody, but also drum and bass? (that would be a reason to apply demucs at input audio even when the model is set as inference mode)

**Comment by nateraw** [comment]
stem separation happens at inference time too. It removes both vocals + drums. You can patch it if you want though, as I do in [this project](https://github.com/nateraw/singing-songstarter) to make it so folks can sing the melody and get a clip conditioned on that.

```python
def _get_stemmed_wav_patched(wav, sample_rate):
    print("Skipping stem separation!")
    return wav

model = musicgen.MusicGen.get_pretrained(model_id)
model.lm.condition_provider.conditioners.self_wav._get_stemmed_wav = _get_stemmed_wav_patched
```

You may find some details in [my blogpost](https://nateraw.com/posts/training_musicgen_songstarter.html#sing-an-idea-prompt-music) about this to be helpful.

**Comment by nateraw** [comment]
the fn we're patching here for reference:

https://github.com/facebookresearch/audiocraft/blob/adf0b04a4452f171970028fcf80f101dd5e26e19/audiocraft/modules/conditioners.py#L603-L614

**Comment by HugoF-Silva** [comment]
thanks!!
