### ISSUE TITLE
Empty output file

### ISSUE THREAD

**Issue by rombirli** [facebookresearch/audiocraft#94]
Good afternoon, 

When I try to generate musics, the output area in the webui is all gray with a download button (but no play button or anything else). 
![image](https://github.com/facebookresearch/audiocraft/assets/56340680/7c26acdb-e5ba-49f5-8ee3-538f6382491c)
When I download the file using this button a 0kB mp4 file is downloaded. Of course i can't open it. Is it a known issue or something to fix it ?
[output.zip](https://github.com/facebookresearch/audiocraft/files/11745540/output.zip)

Thanks in advance for your help

Bests

**Comment by 0RaMsY0** [comment]
You can try and use the demo [here](https://huggingface.co/spaces/facebook/MusicGen) it works fine for me

**Comment by rombirli** [comment]
> Empty output file usually means you have not installed ffmpeg.

Thanks for your help !
