### ISSUE TITLE
Where do models go? 

### ISSUE THREAD

**Issue by gitihobo** [facebookresearch/audiocraft#96]
I want to install the 4 models manually since everytime I try to download state_dict.bin: stops at 67% because of slow download speeds. What do I nedd to install and where?

**Comment by ShmuelRonen** [comment]
![models](https://github.com/facebookresearch/audiocraft/assets/80190186/07f209ab-3de7-4993-97a6-a4fdd1f2f20f)

**Comment by ShmuelRonen** [comment]
![models1](https://github.com/facebookresearch/audiocraft/assets/80190186/b1c2bc4a-ff61-446a-b066-96380ee4a828)

**Comment by gitihobo** [comment]
Awesome thanks
